In [1]:
import numpy as np

In [3]:
A=np.array([[59.4,0.0,4.4,68.4],
           [1.2,104.3,52.0,8.0],
           [1.3,102.2,34.3,2.0]])
print(A)

[[ 59.4   0.    4.4  68.4]
 [  1.2 104.3  52.    8. ]
 [  1.3 102.2  34.3   2. ]]


In [4]:
cal=A.sum(axis=0)
print(cal)

[ 61.9 206.5  90.7  78.4]


In [5]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[95.96122779  0.          4.85115766 87.24489796]
 [ 1.93861066 50.50847458 57.33186329 10.20408163]
 [ 2.10016155 49.49152542 37.81697905  2.55102041]]
